from . import sale_order_channel
from . import sale_order_sync
from . import sale_order_dispatch
from . import stock_picking
from . import whatsapp_notify
from . import config
from . import partner_link
from . import res_partner
from . import phone_link
from . import catalog_menu
from . import category_mirror
from . import money_back
from . import variant_media
from . import variant_desk
from . import sale_order_track
from . import bot_rider
from . import mirrors
from . import sa_hooks
