from . import sale_order_channel
from . import sale_order_sync
from . import sale_order_dispatch
from . import stock_picking
from . import whatsapp_notify
from . import config
from . import partner_link
from . import res_partner
from . import catalog_menu
from . import stock_rule
