from . import loyalty_card
from . import loyalty_card_settings
from . import pos_loyalty_card_image
from . import loyalty_history
from . import loyalty_rule
from . import pos_config
from . import whatsapp_mixin
from . import whatsapp_message
from . import whatsapp_send_queue
from . import whatsapp_campaign
from . import whatsapp_config
from . import whatsapp_session
from . import whatsapp_res_partner
from . import whatsapp_pos_order
from . import baileys_provision
from . import pos_order
from . import res_config_settings
from . import res_partner
from . import whatsapp_service
