from . import test_resolver
from . import test_product_api
from . import test_admin_api
from . import test_builder
from . import test_product_desk
from . import test_product_desk_edit
from . import test_product_form
from . import test_variant_reset
from . import test_variant_media
