"""Generate data/fields.xml - the catalogue of everything the product page
can show.

Run from the module root:  python tools/gen_fields_xml.py

Editing the table below and re-running is the way to add a field; the seeded
record then appears in 369 Mart > Product Page with its own switch.
"""
import io
import pathlib
from xml.etree import ElementTree
from xml.sax.saxutils import escape

HERE = pathlib.Path(__file__).resolve().parent.parent
OUT = HERE / 'data' / 'fields.xml'

# key, label, section, source, odoo_field, default, kind, per_product, note
#
# Only what the product page draws now - the product's own setup, as the
# WhatsApp confirmation page shows it (photos, price, the Variant specs, the
# Sales Description), real reviews and the rails - and each switch here really
# leaves its part out (mart369.product.page). The grocery-template rows (key
# features, product information, returns...) are deleted in
# data/removed_fields.xml.
FIELDS = [
    # -- photos --
    ('images', 'Photos', 'gallery', 'computed', '', '', 'text', 0,
     'Every picture of the product and its variant. Always shown.'),

    # -- buy box --
    ('name', 'Product name', 'buy', 'odoo', 'name', '', 'text', 0,
     'Always shown - a page without a name would be useless.'),
    ('price', 'Price', 'buy', 'odoo', 'list_price', '', 'text', 0,
     'Always shown.'),
    ('mrp', 'MRP and discount', 'buy', 'odoo', 'compare_list_price', '', 'text', 1,
     'The struck-through price and the per-cent-off pill.'),
    ('low_stock', 'Only-N-left warning', 'buy', 'computed', '', '', 'text', 1,
     'Nudges the customer when stock runs low.'),

    # -- specifications --
    ('variant_specs', 'Variant specs', 'specs', 'computed', '', '', 'text', 1,
     "The variant's specs table, as the WhatsApp page lists it (Edit product > Variants)."),

    # -- description --
    ('sales_description', 'Sales Description', 'description', 'odoo', 'description_sale', '',
     'text', 1, 'Shown under the picture on the WhatsApp page and here.'),

    # -- reviews --
    ('rating', 'Average rating', 'reviews', 'computed', '', '', 'text', 1,
     'Worked out from real customer reviews.'),
    ('rating_count', 'Number of ratings', 'reviews', 'computed', '', '', 'text', 1, ''),
    ('rating_bars', 'Star breakdown', 'reviews', 'computed', '', '', 'text', 1,
     'The five-star to one-star bars.'),
    ('reviews', 'Customer reviews', 'reviews', 'computed', '', '', 'text', 1,
     'Written by customers who bought the product.'),
    ('review_empty', 'Be-the-first-to-review line', 'reviews', 'text', '',
     'Be the first to review this product', 'text', 1,
     'Shown instead of the block when there are no reviews yet.'),

    # -- bundle and similar --
    ('bundle_items', 'Frequently bought together', 'bundle', 'computed', '', '', 'text', 1,
     'Uses the accessories set on the product, or picks them automatically.'),
    ('similar_items', 'Similar products', 'similar', 'computed', '', '', 'text', 1,
     'Uses the alternative products set on the product, or the same category.'),
    ('related_items', 'Others you may also like', 'similar', 'computed', '', '', 'text', 1, ''),
]


def build():
    rows = []
    for i, (key, label, sec, source, odoo_field, default, kind, per_product, note) in \
            enumerate(FIELDS, start=1):
        out = [
            '        <record id="f_%s" model="mart369.product.field">' % key,
            '            <field name="key">%s</field>' % key,
            '            <field name="name">%s</field>' % escape(label),
            '            <field name="section_id" ref="sec_%s"/>' % sec,
            '            <field name="sequence">%d</field>' % (i * 10),
            '            <field name="source">%s</field>' % source,
            '            <field name="value_kind">%s</field>' % kind,
        ]
        if odoo_field:
            out.append('            <field name="odoo_field">%s</field>' % odoo_field)
        if default:
            out.append('            <field name="default_value">%s</field>' % escape(default))
        if not per_product:
            out.append('            <field name="per_product" eval="False"/>')
        if note:
            out.append('            <field name="note">%s</field>' % escape(note))
        out.append('        </record>')
        rows.append('\n'.join(out))

    return (
        '<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n'
        '    <!-- Everything the product page can show. Generated by\n'
        '         tools/gen_fields_xml.py - edit the table there and re-run.\n'
        '         noupdate="1" so an upgrade never switches back on something\n'
        '         the shop deliberately switched off. -->\n'
        '    <data noupdate="1">\n\n' + '\n\n'.join(rows) + '\n\n    </data>\n</odoo>\n')


if __name__ == '__main__':
    keys = [f[0] for f in FIELDS]
    assert len(keys) == len(set(keys)), 'duplicate field key'
    OUT.write_text(build(), encoding='utf-8', newline='\n')
    ElementTree.parse(OUT)
    print('wrote %s - %d fields across %d sections'
          % (OUT, len(FIELDS), len({f[2] for f in FIELDS})))
