/* Rebuild static/src/products/editor_look.scss from the web admin's
   components/admin/productDesk.css, so the Odoo editor looks exactly like the
   Next.js one. Run after the web admin's product styles change:

       node odoo_modules/mart369_product/tools/sync_editor_look.js

   The rules are copied as they are, scoped to the 369 Mart screens, with the
   web admin's colour tokens defined under the same names. Only what Odoo's
   libsass cannot read is rewritten (min()/max() with mixed units).
*/
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..", "..");
const src = path.join(root, "components", "admin", "productDesk.css");
const out = path.join(__dirname, "..", "static", "src", "products", "editor_look.scss");

let rules = fs.readFileSync(src, "utf8");
// libsass reads min()/max() as its own functions and fails on mixed units.
rules = rules.replace(/width:\s*min\(([^,]+),\s*100%\)/g, "width: $1; max-width: 100%")
             .replace(/max-height:\s*min\(([^,]+),\s*[^)]+\)/g, "max-height: $1")
             .replace(/\bmin\(([^,()]+),\s*([^()]+)\)/g, "$1")
             .replace(/\bmax\(([^,()]+),\s*([^()]+)\)/g, "$1");
// Links are Odoo's own .mart-link here.
rules = rules.replace(/\.ad-link/g, ".mart-link");

// The admin.css pieces the Products list and editor use (table, pills, tags,
// stock tiles, toolbar, hint, row buttons), copied line for line: each of
// those rules is one line in admin.css.
const ADMIN_PIECES = /^(\.ad-(table|pill|t-|tag|mini-stats|toolbar|hint|cell-person|row-act|strong|more|thumb|stack)|@keyframes ad-(rise|row))/;
const admin = fs.readFileSync(path.join(root, "components", "admin", "admin.css"), "utf8")
    .split("\n").filter((l) => ADMIN_PIECES.test(l)).join("\n");
rules = admin + "\n\n" + rules;

const head = `// GENERATED by tools/sync_editor_look.js from components/admin/productDesk.css.
// Do not edit here: change the web admin's CSS and run the script again.
// Never @import anything here - one local @import breaks the backend bundle.

.o_mart369_desk, .o_mart369_editor_widget {
    --ad-navy: #0b3c58; --ad-blue: #0a78ab; --ad-orange: #f7931e;
    --ad-green: #1a7f3c; --ad-red: #c8433a; --ad-amber: #b7791f; --ad-violet: #7b5cd6;
    --ad-ink: #13212b; --ad-muted: #64757f; --ad-line: #e4eaef; --ad-ground: #f3f6f8; --ad-card: #fff;
    --ad-ease: cubic-bezier(0.22, 1, 0.36, 1); --ad-spring: cubic-bezier(0.34, 1.4, 0.64, 1);

`;
const own = `

/* ---- pieces the web admin takes from admin.css, drawn here the same way
   and under the same names, so the copied rules above find them. */
.ad-card { background: #fff; border: 1px solid var(--ad-line); border-radius: 16px; }
.ad-dim { color: var(--ad-muted); font-size: 12.5px; }
.ad-sm { height: 32px; padding: 0 12px; font-size: 12.5px; display: inline-flex; align-items: center; gap: 6px; }
.ad-icon-btn { width: 32px; height: 32px; display: grid; place-items: center; border: 0; border-radius: 8px; background: none; color: var(--ad-muted); cursor: pointer; flex: none; }
.ad-icon-btn:hover { background: var(--ad-ground); color: var(--ad-ink); }
.ad-search { display: flex; align-items: center; gap: 8px; height: 38px; padding: 0 10px; border: 1px solid var(--ad-line); border-radius: 10px; background: #fff; color: var(--ad-muted); }
.ad-search input { flex: 1; min-width: 0; height: 36px; border: 0 !important; box-shadow: none !important; padding: 0 !important; background: transparent; }

/* ---- Odoo only */
.pdk-form-error { margin: 12px 0 0; }
.pdk-editor { margin-top: 14px; }
/* The panel is sticky under the desk's bar and never taller than the window,
   so all of it can always be seen; it scrolls on its own if it must. On the
   web admin the page is the window; here the desk scrolls inside Odoo, under
   Odoo's own top bar, hence the smaller room. */
.pdk-preview { top: 84px; max-height: calc(100vh - 190px); overflow-y: auto; overscroll-behavior: contain; border-radius: 16px; }
.pdk-embedded .pdk-preview { top: 12px; max-height: calc(100vh - 140px); }
/* The desk scrolls inside a box with 28px of padding on top; the bar sticks
   to the very top of it, with nothing of the form showing above. */
.mart-builder > .pdk-bar { top: -28px; margin-top: -28px; border-radius: 0 0 14px 14px; background: rgba(243, 246, 248, 0.97); }
.pdk-embedded { margin-top: 0; }
/* The dropdowns here are Odoo's Pick; sized like the web admin's selects. */
.pdk-unit .mart-select { flex: 0 0 auto; min-width: 92px; width: auto; }
.pdk-field .mart-select { height: 40px; }
.pdk-field input[type="checkbox"] { height: 18px; width: 18px; }
/* Inside Odoo's product form the sheet is narrower than any window, so the
   web admin's "drop the panel below at 1100px" would always fire and the
   preview would sit under the whole form, out of sight. Here it stays beside
   the form, sticky, as on the web admin; the boxes go to one column instead. */
.pdk-embedded .pdk-cols { grid-template-columns: minmax(0, 1fr) 290px; }
.pdk-embedded .pdk-preview { position: sticky; top: 12px; }
.pdk-embedded .pdk-fields { grid-template-columns: minmax(0, 1fr); }
.pdk-embedded .pdk-mock-card { width: 180px; }
@media (max-width: 1100px) {
    .pdk-embedded .pdk-cols { grid-template-columns: minmax(0, 1fr) 290px; }
    .pdk-embedded .pdk-preview { position: sticky; }
}
@media (max-width: 760px) {
    .pdk-embedded .pdk-cols { grid-template-columns: minmax(0, 1fr); }
    .pdk-embedded .pdk-preview { position: static; }
}
`;
fs.writeFileSync(out, head + rules + own + "\n}\n");
console.log("wrote", path.relative(root, out));
