from . import common
from . import test_channel
from . import test_sync
from . import test_notify
from . import test_rider
from . import test_partner
from . import test_catalog
from . import test_stock
from . import test_money_back
from . import test_store_channel
from . import test_variant_desk
from . import test_web_otp
from . import test_phone_link
from . import test_order_track
from . import test_mirrors
from . import test_sa_hooks
from . import test_staff_alert
from . import test_qe_link
