from . import common
from . import test_channel
from . import test_sync
from . import test_notify
from . import test_rider
from . import test_partner
from . import test_catalog
from . import test_stock
from . import test_money_back
