/* The product page's own parts, as the shop describes them.

   These are the eleven sections and forty-eight fields that mart369_product
   seeds in data/sections.xml and data/fields.xml - keys, names, sources and
   kinds all copied from there, so the screen shows the real page rather than
   an invented one.

   It is a fixture, not an invention, and it is here for one reason: the Odoo
   module has no admin route yet, so there is nothing to fetch. The shape is
   exactly what `mart369.product.field.builder_load()` returns, so wiring this
   screen up later is a change of source, not a change of screen. Until then
   the section carries the console's own "not connected yet" banner.
*/
export const SECTIONS = [
  {
    "id": 1,
    "key": "gallery",
    "name": "Photos",
    "sequence": 10,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 101,
        "key": "images",
        "name": "Photos",
        "sequence": 10,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 102,
        "key": "unit_tag",
        "name": "Size tag on the photo",
        "sequence": 20,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_unit_text",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      }
    ]
  },
  {
    "id": 2,
    "key": "buy",
    "name": "Price and buy box",
    "sequence": 20,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 103,
        "key": "brand",
        "name": "Brand",
        "sequence": 30,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 104,
        "key": "name",
        "name": "Product name",
        "sequence": 40,
        "show": true,
        "source": "odoo",
        "odoo_field": "name",
        "value_kind": "text",
        "per_product": false,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 105,
        "key": "rating_summary",
        "name": "Star rating",
        "sequence": 50,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 106,
        "key": "price",
        "name": "Price",
        "sequence": 60,
        "show": true,
        "source": "odoo",
        "odoo_field": "list_price",
        "value_kind": "text",
        "per_product": false,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 107,
        "key": "mrp",
        "name": "MRP and discount",
        "sequence": 70,
        "show": true,
        "source": "odoo",
        "odoo_field": "compare_list_price",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 108,
        "key": "per_unit",
        "name": "Price per unit",
        "sequence": 80,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 109,
        "key": "low_stock",
        "name": "Only-N-left warning",
        "sequence": 90,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 110,
        "key": "pack_sizes",
        "name": "Pack sizes",
        "sequence": 100,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 111,
        "key": "delivery_mode",
        "name": "Delivery speed badge",
        "sequence": 110,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 112,
        "key": "wishlist",
        "name": "Save-to-list button",
        "sequence": 120,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "bool",
        "per_product": false,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 113,
        "key": "share",
        "name": "Share button",
        "sequence": 130,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "bool",
        "per_product": false,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 3,
    "key": "features",
    "name": "Key features",
    "sequence": 30,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 114,
        "key": "features",
        "name": "Key features",
        "sequence": 140,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_features",
        "value_kind": "lines",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      }
    ]
  },
  {
    "id": 4,
    "key": "info",
    "name": "Product information",
    "sequence": 40,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 115,
        "key": "info_brand",
        "name": "Brand",
        "sequence": 150,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 116,
        "key": "sold_by",
        "name": "Sold by",
        "sequence": 160,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 117,
        "key": "country_of_origin",
        "name": "Country of origin",
        "sequence": 170,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 118,
        "key": "manufacturer_name",
        "name": "Manufacturer name",
        "sequence": 180,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 119,
        "key": "manufacturer_address",
        "name": "Manufacturer address",
        "sequence": 190,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 120,
        "key": "article_id",
        "name": "Article ID",
        "sequence": 200,
        "show": true,
        "source": "odoo",
        "odoo_field": "default_code",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 121,
        "key": "veg",
        "name": "Vegetarian mark",
        "sequence": 210,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_is_veg",
        "value_kind": "bool",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 122,
        "key": "item_height",
        "name": "Item height",
        "sequence": 220,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_item_height",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 123,
        "key": "item_length",
        "name": "Item length",
        "sequence": 230,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_item_length",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 124,
        "key": "item_width",
        "name": "Item width",
        "sequence": 240,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_item_width",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 125,
        "key": "net_weight",
        "name": "Net weight",
        "sequence": 250,
        "show": true,
        "source": "odoo",
        "odoo_field": "weight",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      }
    ]
  },
  {
    "id": 5,
    "key": "specs",
    "name": "Item specifications",
    "sequence": 50,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 126,
        "key": "net_quantity",
        "name": "Net quantity",
        "sequence": 260,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_unit_text",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 127,
        "key": "spec_brand",
        "name": "Brand",
        "sequence": 270,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 128,
        "key": "warranty",
        "name": "Warranty",
        "sequence": 280,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 129,
        "key": "in_the_box",
        "name": "In the box",
        "sequence": 290,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_in_the_box",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 130,
        "key": "material",
        "name": "Material",
        "sequence": 300,
        "show": true,
        "source": "odoo",
        "odoo_field": "mart_material",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 131,
        "key": "product_type",
        "name": "Product type",
        "sequence": 310,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 132,
        "key": "shelf_life",
        "name": "Shelf life",
        "sequence": 320,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 6,
    "key": "description",
    "name": "Description",
    "sequence": 60,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 133,
        "key": "description",
        "name": "Description",
        "sequence": 330,
        "show": true,
        "source": "odoo",
        "odoo_field": "description_ecommerce",
        "value_kind": "html",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "odoo",
        "category_values": []
      },
      {
        "id": 134,
        "key": "disclaimer",
        "name": "Disclaimer",
        "sequence": 340,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 7,
    "key": "returns",
    "name": "Return policy",
    "sequence": 70,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 135,
        "key": "returnable",
        "name": "Returnable",
        "sequence": 350,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "bool",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 136,
        "key": "return_text",
        "name": "Return policy wording",
        "sequence": 360,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 137,
        "key": "policy_link",
        "name": "View-policy link",
        "sequence": 370,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 8,
    "key": "reviews",
    "name": "Ratings and reviews",
    "sequence": 80,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 138,
        "key": "rating",
        "name": "Average rating",
        "sequence": 380,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 139,
        "key": "rating_count",
        "name": "Number of ratings",
        "sequence": 390,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 140,
        "key": "rating_bars",
        "name": "Star breakdown",
        "sequence": 400,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 141,
        "key": "reviews",
        "name": "Customer reviews",
        "sequence": 410,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 142,
        "key": "review_empty",
        "name": "Be-the-first-to-review line",
        "sequence": 420,
        "show": true,
        "source": "text",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 9,
    "key": "delivery",
    "name": "Delivery address",
    "sequence": 90,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 143,
        "key": "address",
        "name": "Delivery address",
        "sequence": 430,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": false,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 144,
        "key": "explore_category",
        "name": "Explore-more link",
        "sequence": 440,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 10,
    "key": "bundle",
    "name": "Frequently bought together",
    "sequence": 100,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 145,
        "key": "bundle_items",
        "name": "Frequently bought together",
        "sequence": 450,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  },
  {
    "id": 11,
    "key": "similar",
    "name": "Similar and related products",
    "sequence": 110,
    "show": true,
    "note": "",
    "rows": [
      {
        "id": 146,
        "key": "similar_items",
        "name": "Similar products",
        "sequence": 460,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 147,
        "key": "related_items",
        "name": "Others you may also like",
        "sequence": 470,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      },
      {
        "id": 148,
        "key": "recently_viewed",
        "name": "Recently viewed",
        "sequence": 480,
        "show": true,
        "source": "computed",
        "odoo_field": "",
        "value_kind": "text",
        "per_product": true,
        "note": "",
        "override_count": 0,
        "state": "follow",
        "visible": true,
        "value": "",
        "product_value": "",
        "has_override": false,
        "value_source": "default",
        "category_values": []
      }
    ]
  }
];

/* A stand-in product, so the canvas has something to draw. Replaced by the
   real card the moment there is a route to ask. */
export const SAMPLE_PRODUCT = {
  id: "sample",
  name: "Mechanical keyboard, hot-swap, 75%",
  unit: "1 piece",
  price: 5499,
  mrp: 7999,
  art: "Keyboard",
  color: "#26323a",
  label: "KEYS",
  images: [],
  stock: 12,
  low: 3,
  cat: "peripherals",
  catName: "Peripherals",
  sub: "keyboards",
  subName: "Keyboards",
};
